[package]
name = "my-redis"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
futures = "0.3.31"
mini-redis = "0.4.1"
tokio = { version = "1.45.1", features = ["full"] }
tokio-stream = "0.1.17"
